/*
 * GUI.java
 *
 * Created on 31 de agosto de 2008, 20:13
 */

package algoritmogenetico;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Administrador
 */
public class GUI extends javax.swing.JFrame {

    private Algoritmo algoritmo;
    
    /** Creates new form GUI */
    public GUI() {
        initComponents();
        algoritmo = new Algoritmo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxLocalizacion = new javax.swing.JComboBox();
        comboBoxBebida = new javax.swing.JComboBox();
        comboBoxComida = new javax.swing.JComboBox();
        checkBoxLocalizacion = new javax.swing.JCheckBox();
        checkBoxBebida = new javax.swing.JCheckBox();
        checkBoxComida = new javax.swing.JCheckBox();
        comboBoxComidaPriorizacion = new javax.swing.JComboBox();
        comboBoxBebidaPriorizacion = new javax.swing.JComboBox();
        comboBoxLocalizacionPriorizacion = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfAltaRango1 = new javax.swing.JTextField();
        tfMediaRango1 = new javax.swing.JTextField();
        tfAltaRango2 = new javax.swing.JTextField();
        tfMediaRango2 = new javax.swing.JTextField();
        tfBajaRango1 = new javax.swing.JTextField();
        tfBajaRango2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOutput = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaCromosoma = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        jLabel1.setText("Priorizacion");

        jLabel2.setText("Localizacion");

        jLabel3.setText("Bebida");

        jLabel4.setText("Comida");

        comboBoxLocalizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));

        comboBoxBebida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));

        comboBoxComida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));

        comboBoxComidaPriorizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sandwiches", "Pollo al champignon", "Caviar", "Asado", "Salmon", "Canapes", "Sushi" }));

        comboBoxBebidaPriorizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Champagne", "Vino", "Agua mineral", "Jugo", "Cerveza", "Sidra", "Gaseosa", "Wisky" }));

        comboBoxLocalizacionPriorizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Club de barrio", "Hotel 5 estrellas", "Hotel 4 estrellas", "Hotel 3 estrellas", "Country", "Local bailable" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(comboBoxComidaPriorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxComida)
                    .addComponent(comboBoxComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(comboBoxBebidaPriorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxBebida)
                    .addComponent(comboBoxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(comboBoxLocalizacionPriorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxLocalizacion)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(checkBoxComida)
                    .addComponent(checkBoxBebida)
                    .addComponent(checkBoxLocalizacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxLocalizacionPriorizacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxBebidaPriorizacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxComidaPriorizacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Config"));

        jLabel5.setText("Alta");

        jLabel6.setText("Media");

        jLabel7.setText("Baja");

        tfAltaRango1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAltaRango1.setText("0.7");

        tfMediaRango1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMediaRango1.setText("0.4");

        tfAltaRango2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAltaRango2.setText("1");

        tfMediaRango2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMediaRango2.setText("0.6");

        tfBajaRango1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBajaRango1.setText("0.1");

        tfBajaRango2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBajaRango2.setText("0.3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfBajaRango1)
                    .addComponent(tfMediaRango1)
                    .addComponent(tfAltaRango1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMediaRango2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(tfBajaRango2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(tfAltaRango2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfAltaRango1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfMediaRango1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMediaRango2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfBajaRango1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBajaRango2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfAltaRango2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Generar Algoritmo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        tableOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comida", "Bebida", "Localizacion", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOutput);
        tableOutput.getColumnModel().getColumn(0).setResizable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );

        textAreaCromosoma.setColumns(20);
        textAreaCromosoma.setRows(5);
        jScrollPane2.setViewportView(textAreaCromosoma);

        jButton2.setText("Ver mejor Cromosoma");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(5, 5, 5)
                        .addComponent(jButton2))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    ArrayList<Integer> datosIngresados = cargarDatosIngresados();
    HashMap<String,String> priorizacion = cargarPriorizacion();
    double[][] rangoDefault = cargarRangoDefault();
    algoritmo.datosIngresados = datosIngresados;
    algoritmo.priorizacion = priorizacion;
    algoritmo.rangoDefault = rangoDefault;
    algoritmo.iniciar();
    cargarTabla();
}//GEN-LAST:event_jButton1ActionPerformed



private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    textAreaCromosoma.setText("");
    int aux = tableOutput.getRowCount();
    DefaultTableModel model = (DefaultTableModel) tableOutput.getModel();
    HashMap<String,HashMap<ArrayList<String>,Double>> mapa = algoritmo.getMapaDetodo();
    int aux2 = 0;
    for(int i=0 ; i < aux ; i++){
        if(Double.parseDouble(model.getValueAt(i, 3).toString()) == 0D){
            textAreaCromosoma.append("Cromosoma Numero:"+ (++aux2) +"\n\n");
            textAreaCromosoma.append("Comida:\n");
            HashMap<ArrayList<String>,Double> lista1 = mapa.get("Comida");
            Iterator it = lista1.keySet().iterator();
            Collection<Double> col = lista1.values();
            Iterator it2 = col.iterator();
            while(it2.hasNext()){
                Double valor = (Double) it2.next();
                ArrayList<String> listaa = (ArrayList<String>) it.next();
                if(valor == Double.parseDouble(model.getValueAt(i, 0).toString())){
                    for(int j=0 ; j < listaa.size() ; j++){
                        textAreaCromosoma.append("\t"+listaa.get(j)+"\n");
                    }
                    break;
                }
            }
            
            textAreaCromosoma.append("\n");
            textAreaCromosoma.append("Bebida:\n");
            lista1 = mapa.get("Bebida");
            it = lista1.keySet().iterator();
            col = lista1.values();
            it2 = col.iterator();
            while(it2.hasNext()){
                Double valor = (Double) it2.next();
                ArrayList<String> listaa = (ArrayList<String>) it.next();
                if(valor == Double.parseDouble(model.getValueAt(i, 1).toString())){
                    for(int j=0 ; j < listaa.size() ; j++){
                        textAreaCromosoma.append("\t"+listaa.get(j)+"\n");
                        
                    }
                    break;
                }
            }
            textAreaCromosoma.append("\n");
            textAreaCromosoma.append("Localizacion:\n");
            lista1 = mapa.get("Localizacion");
            it = lista1.keySet().iterator();
            col = lista1.values();
            it2 = col.iterator();
            while(it2.hasNext()){
                Double valor = (Double) it2.next();
                ArrayList<String> listaa = (ArrayList<String>) it.next();
                if(valor == Double.parseDouble(model.getValueAt(i, 2).toString())){
                    for(int j=0 ; j < listaa.size() ; j++){
                        textAreaCromosoma.append("\t"+listaa.get(j)+"\n");
                        
                    }
                    break;
                }
            }
            textAreaCromosoma.append("\n\n\n");
        }
    }
}//GEN-LAST:event_jButton2ActionPerformed

public void cargarTabla(){
    ArrayList<ArrayList<Double>> poblacionFinal = algoritmo.poblacionFinal;
    ArrayList<Double> pesoFinal = algoritmo.pesoFinal;
    DefaultTableModel model = (DefaultTableModel) tableOutput.getModel();
    vaciarTabla();
    for(int i=2 ; i < poblacionFinal.size() ; i++){
        ArrayList<Double> aux = poblacionFinal.get(i);
        model.addRow( new Double[]{aux.get(0),aux.get(1),aux.get(2),pesoFinal.get(i)});
    }
}
public void vaciarTabla() {
        ((DefaultTableModel)tableOutput.getModel()).getDataVector().removeAllElements();
}

public double[][] cargarRangoDefault(){
    double[][] aux = new double[3][2];
    aux[0][0] = Double.parseDouble(tfAltaRango1.getText());
    aux[0][1] = Double.parseDouble(tfAltaRango2.getText());
    aux[1][0] = Double.parseDouble(tfMediaRango1.getText());
    aux[1][1] = Double.parseDouble(tfMediaRango2.getText());
    aux[2][0] = Double.parseDouble(tfBajaRango1.getText());
    aux[2][1] = Double.parseDouble(tfBajaRango2.getText());
    return aux;
}

public HashMap<String,String> cargarPriorizacion(){
    HashMap<String,String> hash = new HashMap<String,String>();
    if(checkBoxComida.isSelected()){
        hash.put("Comida", comboBoxComidaPriorizacion.getSelectedItem().toString());
    }    
    if(checkBoxBebida.isSelected()){
        hash.put("Bebida", comboBoxBebidaPriorizacion.getSelectedItem().toString());
    }
    if(checkBoxLocalizacion.isSelected()){
        hash.put("Localizacion", comboBoxLocalizacionPriorizacion.getSelectedItem().toString());
    }   
    return hash;
}

public ArrayList<Integer> cargarDatosIngresados(){
    ArrayList<Integer> aux = new ArrayList<Integer>();
    int valor[] = new int[3];
    valor[0] = comboBoxComida.getSelectedIndex() + 1;
    valor[1] = comboBoxBebida.getSelectedIndex() + 1;
    valor[2] = comboBoxLocalizacion.getSelectedIndex() + 1;
    for(int i=0 ; i < valor.length ; i++){
        aux.add(valor[i]);
    }
    return aux;
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxBebida;
    private javax.swing.JCheckBox checkBoxComida;
    private javax.swing.JCheckBox checkBoxLocalizacion;
    private javax.swing.JComboBox comboBoxBebida;
    private javax.swing.JComboBox comboBoxBebidaPriorizacion;
    private javax.swing.JComboBox comboBoxComida;
    private javax.swing.JComboBox comboBoxComidaPriorizacion;
    private javax.swing.JComboBox comboBoxLocalizacion;
    private javax.swing.JComboBox comboBoxLocalizacionPriorizacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableOutput;
    private javax.swing.JTextArea textAreaCromosoma;
    private javax.swing.JTextField tfAltaRango1;
    private javax.swing.JTextField tfAltaRango2;
    private javax.swing.JTextField tfBajaRango1;
    private javax.swing.JTextField tfBajaRango2;
    private javax.swing.JTextField tfMediaRango1;
    private javax.swing.JTextField tfMediaRango2;
    // End of variables declaration//GEN-END:variables

}
